#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlguSkaiciuokle2019
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlguSkaiciuokle2019DB")]
	public partial class MokesciaiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMokesciai(Mokesciai instance);
    partial void UpdateMokesciai(Mokesciai instance);
    partial void DeleteMokesciai(Mokesciai instance);
    #endregion
		
		public MokesciaiDataContext() : 
				base(global::AlguSkaiciuokle2019.Properties.Settings.Default.AlguSkaiciuokle2019DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MokesciaiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MokesciaiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MokesciaiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MokesciaiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Mokesciai> Mokesciais
		{
			get
			{
				return this.GetTable<Mokesciai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mokesciai")]
	public partial class Mokesciai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tipas;
		
		private System.Nullable<double> _SveikatosDraudimo;
		
		private System.Nullable<double> _PensijuIrSocDraudimo;
		
		private System.Nullable<double> _Pajamu;
		
		private System.Nullable<double> _Darbdavio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTipasChanging(string value);
    partial void OnTipasChanged();
    partial void OnSveikatosDraudimoChanging(System.Nullable<double> value);
    partial void OnSveikatosDraudimoChanged();
    partial void OnPensijuIrSocDraudimoChanging(System.Nullable<double> value);
    partial void OnPensijuIrSocDraudimoChanged();
    partial void OnPajamuChanging(System.Nullable<double> value);
    partial void OnPajamuChanged();
    partial void OnDarbdavioChanging(System.Nullable<double> value);
    partial void OnDarbdavioChanged();
    #endregion
		
		public Mokesciai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipas", DbType="NVarChar(11)")]
		public string Tipas
		{
			get
			{
				return this._Tipas;
			}
			set
			{
				if ((this._Tipas != value))
				{
					this.OnTipasChanging(value);
					this.SendPropertyChanging();
					this._Tipas = value;
					this.SendPropertyChanged("Tipas");
					this.OnTipasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SveikatosDraudimo", DbType="Float")]
		public System.Nullable<double> SveikatosDraudimo
		{
			get
			{
				return this._SveikatosDraudimo;
			}
			set
			{
				if ((this._SveikatosDraudimo != value))
				{
					this.OnSveikatosDraudimoChanging(value);
					this.SendPropertyChanging();
					this._SveikatosDraudimo = value;
					this.SendPropertyChanged("SveikatosDraudimo");
					this.OnSveikatosDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PensijuIrSocDraudimo", DbType="Float")]
		public System.Nullable<double> PensijuIrSocDraudimo
		{
			get
			{
				return this._PensijuIrSocDraudimo;
			}
			set
			{
				if ((this._PensijuIrSocDraudimo != value))
				{
					this.OnPensijuIrSocDraudimoChanging(value);
					this.SendPropertyChanging();
					this._PensijuIrSocDraudimo = value;
					this.SendPropertyChanged("PensijuIrSocDraudimo");
					this.OnPensijuIrSocDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pajamu", DbType="Float")]
		public System.Nullable<double> Pajamu
		{
			get
			{
				return this._Pajamu;
			}
			set
			{
				if ((this._Pajamu != value))
				{
					this.OnPajamuChanging(value);
					this.SendPropertyChanging();
					this._Pajamu = value;
					this.SendPropertyChanged("Pajamu");
					this.OnPajamuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darbdavio", DbType="Float")]
		public System.Nullable<double> Darbdavio
		{
			get
			{
				return this._Darbdavio;
			}
			set
			{
				if ((this._Darbdavio != value))
				{
					this.OnDarbdavioChanging(value);
					this.SendPropertyChanging();
					this._Darbdavio = value;
					this.SendPropertyChanged("Darbdavio");
					this.OnDarbdavioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
