#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlguSkaiciuokle2019
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlguSkaiciuokle2019DB")]
	public partial class SkaiciavimaiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSkaiciavimai(Skaiciavimai instance);
    partial void UpdateSkaiciavimai(Skaiciavimai instance);
    partial void DeleteSkaiciavimai(Skaiciavimai instance);
    #endregion
		
		public SkaiciavimaiDataContext() : 
				base(global::AlguSkaiciuokle2019.Properties.Settings.Default.AlguSkaiciuokle2019DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SkaiciavimaiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SkaiciavimaiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SkaiciavimaiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SkaiciavimaiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Skaiciavimai> Skaiciavimais
		{
			get
			{
				return this.GetTable<Skaiciavimai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Skaiciavimai")]
	public partial class Skaiciavimai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _VardasPavarde;
		
		private System.Nullable<double> _EurAlgaAntPopieriaus;
		
		private System.Nullable<double> _EurAlgaIRankas;
		
		private System.Nullable<double> _EurAAlgaAntPopieriaus;
		
		private System.Nullable<double> _EurAAlgaIRankas;
		
		private System.Nullable<double> _EurSveikatosDraudimo;
		
		private System.Nullable<double> _EurPensijuIrSocDraudimo;
		
		private System.Nullable<double> _EurPajamu;
		
		private System.Nullable<double> _EurDarbdavio;
		
		private System.Nullable<double> _EurAutorSveikatosDraudimo;
		
		private System.Nullable<double> _EurAutorPajamu;
		
		private System.Nullable<double> _SveikatosDraudimo;
		
		private System.Nullable<double> _PensijuIrSocDraudimo;
		
		private System.Nullable<double> _Pajamu;
		
		private System.Nullable<double> _Darbdavio;
		
		private System.Nullable<double> _AutorSveikatosDraudimo;
		
		private System.Nullable<double> _AutorPajamu;
		
		private System.Nullable<int> _DarbuotojoId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVardasPavardeChanging(string value);
    partial void OnVardasPavardeChanged();
    partial void OnEurAlgaAntPopieriausChanging(System.Nullable<double> value);
    partial void OnEurAlgaAntPopieriausChanged();
    partial void OnEurAlgaIRankasChanging(System.Nullable<double> value);
    partial void OnEurAlgaIRankasChanged();
    partial void OnEurAAlgaAntPopieriausChanging(System.Nullable<double> value);
    partial void OnEurAAlgaAntPopieriausChanged();
    partial void OnEurAAlgaIRankasChanging(System.Nullable<double> value);
    partial void OnEurAAlgaIRankasChanged();
    partial void OnEurSveikatosDraudimoChanging(System.Nullable<double> value);
    partial void OnEurSveikatosDraudimoChanged();
    partial void OnEurPensijuIrSocDraudimoChanging(System.Nullable<double> value);
    partial void OnEurPensijuIrSocDraudimoChanged();
    partial void OnEurPajamuChanging(System.Nullable<double> value);
    partial void OnEurPajamuChanged();
    partial void OnEurDarbdavioChanging(System.Nullable<double> value);
    partial void OnEurDarbdavioChanged();
    partial void OnEurAutorSveikatosDraudimoChanging(System.Nullable<double> value);
    partial void OnEurAutorSveikatosDraudimoChanged();
    partial void OnEurAutorPajamuChanging(System.Nullable<double> value);
    partial void OnEurAutorPajamuChanged();
    partial void OnSveikatosDraudimoChanging(System.Nullable<double> value);
    partial void OnSveikatosDraudimoChanged();
    partial void OnPensijuIrSocDraudimoChanging(System.Nullable<double> value);
    partial void OnPensijuIrSocDraudimoChanged();
    partial void OnPajamuChanging(System.Nullable<double> value);
    partial void OnPajamuChanged();
    partial void OnDarbdavioChanging(System.Nullable<double> value);
    partial void OnDarbdavioChanged();
    partial void OnAutorSveikatosDraudimoChanging(System.Nullable<double> value);
    partial void OnAutorSveikatosDraudimoChanged();
    partial void OnAutorPajamuChanging(System.Nullable<double> value);
    partial void OnAutorPajamuChanged();
    partial void OnDarbuotojoIdChanging(System.Nullable<int> value);
    partial void OnDarbuotojoIdChanged();
    #endregion
		
		public Skaiciavimai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VardasPavarde", DbType="NVarChar(50)")]
		public string VardasPavarde
		{
			get
			{
				return this._VardasPavarde;
			}
			set
			{
				if ((this._VardasPavarde != value))
				{
					this.OnVardasPavardeChanging(value);
					this.SendPropertyChanging();
					this._VardasPavarde = value;
					this.SendPropertyChanged("VardasPavarde");
					this.OnVardasPavardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurAlgaAntPopieriaus", DbType="Float")]
		public System.Nullable<double> EurAlgaAntPopieriaus
		{
			get
			{
				return this._EurAlgaAntPopieriaus;
			}
			set
			{
				if ((this._EurAlgaAntPopieriaus != value))
				{
					this.OnEurAlgaAntPopieriausChanging(value);
					this.SendPropertyChanging();
					this._EurAlgaAntPopieriaus = value;
					this.SendPropertyChanged("EurAlgaAntPopieriaus");
					this.OnEurAlgaAntPopieriausChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurAlgaIRankas", DbType="Float")]
		public System.Nullable<double> EurAlgaIRankas
		{
			get
			{
				return this._EurAlgaIRankas;
			}
			set
			{
				if ((this._EurAlgaIRankas != value))
				{
					this.OnEurAlgaIRankasChanging(value);
					this.SendPropertyChanging();
					this._EurAlgaIRankas = value;
					this.SendPropertyChanged("EurAlgaIRankas");
					this.OnEurAlgaIRankasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurAAlgaAntPopieriaus", DbType="Float")]
		public System.Nullable<double> EurAAlgaAntPopieriaus
		{
			get
			{
				return this._EurAAlgaAntPopieriaus;
			}
			set
			{
				if ((this._EurAAlgaAntPopieriaus != value))
				{
					this.OnEurAAlgaAntPopieriausChanging(value);
					this.SendPropertyChanging();
					this._EurAAlgaAntPopieriaus = value;
					this.SendPropertyChanged("EurAAlgaAntPopieriaus");
					this.OnEurAAlgaAntPopieriausChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurAAlgaIRankas", DbType="Float")]
		public System.Nullable<double> EurAAlgaIRankas
		{
			get
			{
				return this._EurAAlgaIRankas;
			}
			set
			{
				if ((this._EurAAlgaIRankas != value))
				{
					this.OnEurAAlgaIRankasChanging(value);
					this.SendPropertyChanging();
					this._EurAAlgaIRankas = value;
					this.SendPropertyChanged("EurAAlgaIRankas");
					this.OnEurAAlgaIRankasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurSveikatosDraudimo", DbType="Float")]
		public System.Nullable<double> EurSveikatosDraudimo
		{
			get
			{
				return this._EurSveikatosDraudimo;
			}
			set
			{
				if ((this._EurSveikatosDraudimo != value))
				{
					this.OnEurSveikatosDraudimoChanging(value);
					this.SendPropertyChanging();
					this._EurSveikatosDraudimo = value;
					this.SendPropertyChanged("EurSveikatosDraudimo");
					this.OnEurSveikatosDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurPensijuIrSocDraudimo", DbType="Float")]
		public System.Nullable<double> EurPensijuIrSocDraudimo
		{
			get
			{
				return this._EurPensijuIrSocDraudimo;
			}
			set
			{
				if ((this._EurPensijuIrSocDraudimo != value))
				{
					this.OnEurPensijuIrSocDraudimoChanging(value);
					this.SendPropertyChanging();
					this._EurPensijuIrSocDraudimo = value;
					this.SendPropertyChanged("EurPensijuIrSocDraudimo");
					this.OnEurPensijuIrSocDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurPajamu", DbType="Float")]
		public System.Nullable<double> EurPajamu
		{
			get
			{
				return this._EurPajamu;
			}
			set
			{
				if ((this._EurPajamu != value))
				{
					this.OnEurPajamuChanging(value);
					this.SendPropertyChanging();
					this._EurPajamu = value;
					this.SendPropertyChanged("EurPajamu");
					this.OnEurPajamuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurDarbdavio", DbType="Float")]
		public System.Nullable<double> EurDarbdavio
		{
			get
			{
				return this._EurDarbdavio;
			}
			set
			{
				if ((this._EurDarbdavio != value))
				{
					this.OnEurDarbdavioChanging(value);
					this.SendPropertyChanging();
					this._EurDarbdavio = value;
					this.SendPropertyChanged("EurDarbdavio");
					this.OnEurDarbdavioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurAutorSveikatosDraudimo", DbType="Float")]
		public System.Nullable<double> EurAutorSveikatosDraudimo
		{
			get
			{
				return this._EurAutorSveikatosDraudimo;
			}
			set
			{
				if ((this._EurAutorSveikatosDraudimo != value))
				{
					this.OnEurAutorSveikatosDraudimoChanging(value);
					this.SendPropertyChanging();
					this._EurAutorSveikatosDraudimo = value;
					this.SendPropertyChanged("EurAutorSveikatosDraudimo");
					this.OnEurAutorSveikatosDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EurAutorPajamu", DbType="Float")]
		public System.Nullable<double> EurAutorPajamu
		{
			get
			{
				return this._EurAutorPajamu;
			}
			set
			{
				if ((this._EurAutorPajamu != value))
				{
					this.OnEurAutorPajamuChanging(value);
					this.SendPropertyChanging();
					this._EurAutorPajamu = value;
					this.SendPropertyChanged("EurAutorPajamu");
					this.OnEurAutorPajamuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SveikatosDraudimo", DbType="Float")]
		public System.Nullable<double> SveikatosDraudimo
		{
			get
			{
				return this._SveikatosDraudimo;
			}
			set
			{
				if ((this._SveikatosDraudimo != value))
				{
					this.OnSveikatosDraudimoChanging(value);
					this.SendPropertyChanging();
					this._SveikatosDraudimo = value;
					this.SendPropertyChanged("SveikatosDraudimo");
					this.OnSveikatosDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PensijuIrSocDraudimo", DbType="Float")]
		public System.Nullable<double> PensijuIrSocDraudimo
		{
			get
			{
				return this._PensijuIrSocDraudimo;
			}
			set
			{
				if ((this._PensijuIrSocDraudimo != value))
				{
					this.OnPensijuIrSocDraudimoChanging(value);
					this.SendPropertyChanging();
					this._PensijuIrSocDraudimo = value;
					this.SendPropertyChanged("PensijuIrSocDraudimo");
					this.OnPensijuIrSocDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pajamu", DbType="Float")]
		public System.Nullable<double> Pajamu
		{
			get
			{
				return this._Pajamu;
			}
			set
			{
				if ((this._Pajamu != value))
				{
					this.OnPajamuChanging(value);
					this.SendPropertyChanging();
					this._Pajamu = value;
					this.SendPropertyChanged("Pajamu");
					this.OnPajamuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darbdavio", DbType="Float")]
		public System.Nullable<double> Darbdavio
		{
			get
			{
				return this._Darbdavio;
			}
			set
			{
				if ((this._Darbdavio != value))
				{
					this.OnDarbdavioChanging(value);
					this.SendPropertyChanging();
					this._Darbdavio = value;
					this.SendPropertyChanged("Darbdavio");
					this.OnDarbdavioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorSveikatosDraudimo", DbType="Float")]
		public System.Nullable<double> AutorSveikatosDraudimo
		{
			get
			{
				return this._AutorSveikatosDraudimo;
			}
			set
			{
				if ((this._AutorSveikatosDraudimo != value))
				{
					this.OnAutorSveikatosDraudimoChanging(value);
					this.SendPropertyChanging();
					this._AutorSveikatosDraudimo = value;
					this.SendPropertyChanged("AutorSveikatosDraudimo");
					this.OnAutorSveikatosDraudimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutorPajamu", DbType="Float")]
		public System.Nullable<double> AutorPajamu
		{
			get
			{
				return this._AutorPajamu;
			}
			set
			{
				if ((this._AutorPajamu != value))
				{
					this.OnAutorPajamuChanging(value);
					this.SendPropertyChanging();
					this._AutorPajamu = value;
					this.SendPropertyChanged("AutorPajamu");
					this.OnAutorPajamuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DarbuotojoId", DbType="Int")]
		public System.Nullable<int> DarbuotojoId
		{
			get
			{
				return this._DarbuotojoId;
			}
			set
			{
				if ((this._DarbuotojoId != value))
				{
					this.OnDarbuotojoIdChanging(value);
					this.SendPropertyChanging();
					this._DarbuotojoId = value;
					this.SendPropertyChanged("DarbuotojoId");
					this.OnDarbuotojoIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
